language: generic

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

os: linux

# The apt packages below are needed for sphinx builds. A full list of
# packages that can be included can be found here:
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
    apt:
        packages:
            - gfortran

env:
    global:
        - PYTHON_VERSION=3.7
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='scipy scikit-learn matplotlib pymc'
        - PIP_DEPENDENCIES='astroML_addons'
        - DEBUG=true
        - PYTEST_VERSION='<4'

matrix:
    fast_finish: true

    include:
        - env: NUMPY_VERSION=1.15

        - env: NUMPY_VERSION=1.14

        - env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.13

        - env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.12

        - env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.11

        - env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.10 SCIKIT_LEARN_VERSION=0.18

        - env: PYTHON_VERSION=3.4 CONDA_DEPENDENCIES='scipy matplotlib pymc' NUMPY_VERSION=1.9
               PIP_DEPENDENCIES='astropy==2.0.9 scikit-learn==0.18'

        - env: PYTHON_VERSION=2.7

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python setup.py install

script:
    - pytest astroML
